Final changes

diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -2,47 +2,47 @@ name: Prepare release draft with built binaries
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - aa/testnet-release-template
 
 concurrency:
   group: ${{ github.workflow }}@${{ github.ref_name }}
   cancel-in-progress: true
 
 jobs:
-  setup:
-    name: Define variables and configure environment
+  configure-version:
+    name: Configure release version
+    if: ${{ github.ref_type == 'tag' }}
     runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.define-version.outputs.version }}
+
     steps:
+      # Takes the version of the tag from which the workflow is dispatched (or fails if the workflow was not dispatched from a tag).
+      # Also, it uses a special tag name `release-ci-test` to indicate a test run, in which case the release version is set to `0.0.0`, and should be used for test reasons only.
       - name: Define version
         id: define-version
         env:
-          VERSION: ${{ github.ref_name }}
+          TAG_NAME: ${{ github.ref_name }}
         run: |
-          # if [[ "${{ github.ref_type }}" != "tag" ]]; then
-          #   echo "This workflow must be dispatched from a tag, not a branch."
-          #   exit 1
-          # fi
+          if [[ "$TAG_NAME" == "release-ci-test" ]]; then
+            echo "Test workflow run. Setting version to 0.0.0 for testing."
+            VERSION=0.0.0
+          elif [[ "$TAG_NAME" =~ ^([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
+            echo "Release workflow run for tag '$TAG_NAME'. Setting version to '$TAG_NAME'."
+            VERSION="$TAG_NAME"
+          else
+            echo "Tag name '$TAG_NAME' is not valid. It must either be 'release-ci-test' or follow the format 'X.Y.Z'."
+            exit 1
+          fi
 
-          # if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          #   echo "VERSION must follow the format of 'X.Y.Z'. Value: '$VERSION'."
-          #   exit 2
-          # fi
-
-          # echo "version=$VERSION" >> $GITHUB_OUTPUT
-          
-          echo "version=0.1.0" >> $GITHUB_OUTPUT
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
 
   build:
     name: "Build binaries for ${{ matrix.platform.os-display }} (${{ matrix.platform.arch }})"
-    needs: setup
+    needs: configure-version
+    runs-on: ${{ matrix.platform.builder }}
     env:
-      VERSION: ${{ needs.setup.outputs.version }}
+      VERSION: ${{ needs.configure-version.outputs.version }}
     strategy:
-      fail-fast: false
       matrix:
         platform:
           - os: linux
@@ -53,7 +53,7 @@ jobs:
           - os: linux
             os-display: Linux
             arch: aarch64
-            builder: ubuntu-22.04-arm
+            builder: ubuntu-24.04-arm
             target_triple: aarch64-unknown-linux-gnu
           - os: macos
             os-display: MacOS
@@ -61,12 +61,11 @@ jobs:
             builder: macos-14
             target_triple: aarch64-apple-darwin
 
-    runs-on: ${{ matrix.platform.builder }}
     steps:
       - name: Checkout
         uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
 
-      - name: Add the target toolchain
+      - name: Add the target triple
         run: rustup target add ${{ matrix.platform.target_triple }}
 
       - name: Setup Circuits
@@ -74,36 +73,34 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - uses: actions-rs/cargo@9e120dd99b0fbad1c065f686657e914e76bd7b72  # Version 1.0.1
-        name: Build node binary
-        with:
-          command: build
-          args: -p logos-blockchain-node --target ${{ matrix.platform.target_triple }}
+      - name: Build node binary
+        run: cargo build -p logos-blockchain-node --release --target ${{ matrix.platform.target_triple }}
 
       - name: Upload binary (${{ matrix.platform.arch }})
         uses: actions/upload-artifact@6027e3dd177782cd8ab9af838c04fd81a07f1d47 # Version 4.6.2
         with:
-          name: logos-blockchain-node-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ needs.setup.outputs.version }}
-          path: target/${{ matrix.platform.target_triple }}/debug/logos-blockchain-node
+          name: logos-blockchain-node-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ needs.configure-version.outputs.version }}
+          path: target/${{ matrix.platform.target_triple }}/release/logos-blockchain-node
           if-no-files-found: error
 
-  create-release:
-    name: Create release
+  create-draft-release:
+    name: Create draft release
     needs:
-      - setup
+      - configure-version
       - build
     runs-on: ubuntu-latest
     env:
-      VERSION: ${{ needs.setup.outputs.version }}
+      VERSION: ${{ needs.configure-version.outputs.version }}
     outputs:
-      upload_url: ${{ steps.create_release.outputs.upload_url }}
+      upload_url: ${{ steps.create-draft-release.outputs.upload_url }}
+
     steps:
       - name: Checkout
         uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
 
-      - name: Create Release
+      - name: Create Draft Release
         uses: actions/create-release@4c11c9fe1dcd9636620a16455165783b20fc7ea0  # Version 1.1.4
-        id: create_release
+        id: create-draft-release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
@@ -114,10 +111,10 @@ jobs:
           prerelease: true
 
   upload-artifacts:
-    name: Upload Artifacts to release
+    name: Upload artifacts to release
     needs:
-      - setup
-      - create-release
+      - configure-version
+      - create-draft-release
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -128,20 +125,20 @@ jobs:
             arch: aarch64
           - os: macos
             arch: aarch64
-
     env:
-      UPLOAD_URL: ${{ needs.create-release.outputs.upload_url }}
-      BINARY_NAME: logos-blockchain-node-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ needs.setup.outputs.version }}
+      UPLOAD_URL: ${{ needs.create-draft-release.outputs.upload_url }}
+      BINARY_NAME: logos-blockchain-node-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ needs.configure-version.outputs.version }}
       DOWNLOAD_DIRECTORY: artifacts
+
     steps:
-      - name: Download Artifact
+      - name: Download artifact
         uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # Version 4.2.1
         with:
           name: ${{ env.BINARY_NAME }}
           path: ${{ env.DOWNLOAD_DIRECTORY }}
           merge-multiple: true
 
-      - name: Upload ${{ matrix.platform.os }} (${{ matrix.platform.arch }})
+      - name: Upload ${{ matrix.platform.os }} (${{ matrix.platform.arch }}) to release
         uses: actions/upload-release-asset@ef2adfe8cb8ebfa540930c452c576b3819990faa  # Version 1.0.2
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -152,12 +149,13 @@ jobs:
           asset_content_type: application/octet-stream
 
   upload-node-config:
-    name: Upload node config file to release
+    name: Upload example node config to release
     needs:
-      - create-release
+      - create-draft-release
     runs-on: ubuntu-latest
     env:
-      UPLOAD_URL: ${{ needs.create-release.outputs.upload_url }}
+      UPLOAD_URL: ${{ needs.create-draft-release.outputs.upload_url }}
+
     steps:
       - name: Checkout
         uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2  # Version 4.2.2
